### ISSUE TITLE
Unplayable run

### ISSUE THREAD

**Issue by DSF100** [RexcellentGames/BurningKnight#2]
![image](https://user-images.githubusercontent.com/33063517/66846591-13981900-ef83-11e9-9d8d-17e6c4f5bd4c.png)

Some run such as this one cannot be completed due to some room being kinda weird.

**Comment by egordorichev** [comment]
Can you send me a screenshot of the room? There was a recent patch for some unpassable room, I hope that's the one. Didn't push it yet.
