### ISSUE TITLE
Room orientation

### ISSUE THREAD

**Issue by DSF100** [RexcellentGames/BurningKnight#3]
the photo speaks by itself
![image](https://user-images.githubusercontent.com/33063517/66847995-5d81fe80-ef85-11e9-97af-011ffb6f0ae3.png)

**Comment by egordorichev** [comment]
Did the machine block exit?

**Comment by DSF100** [comment]
> Did the machine block exit?

yep

**Comment by egordorichev** [comment]
Should be fixed now.
