### ISSUE TITLE
Graphical glitch with flashes off

### ISSUE THREAD

**Issue by Vegechu** [RexcellentGames/BurningKnight#45]
When playing with flashes off, the screen contracts a lot for a single frame when there would've been a flash otherwise.
Vid: https://files.catbox.moe/jbxphn.webm
![bk mp4_snapshot_00 00_ 2020 07 12_16 39 19](https://user-images.githubusercontent.com/41387120/87249273-807f0780-c45e-11ea-9872-f2d2af7b93c6.jpg)

**Comment by egordorichev** [comment]
This is not a bug, this special effect was always there. But i agree, it will be disabled with flash setting in the next update.
